export const USER_RETRIEVED = 'USER_RETRIEVED';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const GOT_USER_INFO = 'GOT_USER_INFO';

export const GOT_A_COLLECTION = 'GOT_A_COLLECTION';
export const GOT_USER_COLLECTIONS_LIST = 'GOT_USER_COLLECTIONS_LIST';
export const GOT_PUBLIC_COLLECTIONS_LIST = 'GOT_PUBLIC_COLLECTIONS_LIST';

export const GOT_SEARCH_RESULTS = 'GOT_SEARCH_RESULTS';
export const GOT_MORE_SEARCH_RESULTS = 'GOT_MORE_SEARCH_RESULTS';
export const FAILED_SEARCH_RESULTS = 'FAILED_SEARCH_RESULTS';

export const GOT_PHOTOS = 'GOT_PHOTOS';
export const GOT_MORE_PHOTOS = 'GOT_MORE_PHOTOS';
export const GOT_PHOTOS_ERROR = 'GOT_PHOTOS_ERROR';
