export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const GOT_USER_INFO = 'GOT_USER_INFO'

export const GOT_COLLECTIONS_LIST = 'GOT_COLLECTIONS_LIST'
